markdown: rdiscount
pygments: true

youyan: your_id # youyan id
data_sources:
  - name: wedding # will be used as site.albums to access data, no spaces allowed
    type: json
    url:  http://i.91wedding.com/sites/classic/data # must be http or https
